#fmt enforcer.
repos:
  - repo: local
    hooks:
      - id: terraform-fmt-check
        name: terraform fmt (check)
        entry: terraform fmt -recursive -check
        language: system
        files: "\\.tf$"
        stages: [pre-push]

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "3.2.508" # change to tag or sha
    hooks:
      - id: checkov
        name: Checkov
        entry: checkov -d infra
        language: python
        types: [terraform]
        stages: [pre-push]
